nutrition_blog/nutrition_blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
        path('admin/', admin.site.urls),
        path('', include('nutrition_blog.web.urls')),
        path('accounts/', include('nutrition_blog.accounts.urls')),
        path('email/', include('nutrition_blog.email_client.urls')),


]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

nutrition_blog/nutrition_blog/web/models.py
from django.contrib.auth import get_user_model
from django.db import models

from nutrition_blog.accounts.models import Profile, AppUser

UserModel = get_user_model()


class Articles(models.Model):
    ARTICLE_NAME_MAX_LEN = 15
    ARTICLE_TAG_NAME_MAX_LEN = 15

    article_url_image = models.URLField(
            default = "https://cfpen.org/wp-content/uploads/2019/05/Eat_Healthy_Blog_15May19.jpg",
    )
    article_tag_name = models.CharField(
            max_length = ARTICLE_TAG_NAME_MAX_LEN,
            default = "Tips",
    )

    article_title = models.CharField(
            max_length = ARTICLE_NAME_MAX_LEN,
            default = "Healthy Advice",
    )

    description = models.TextField(
            default = 'Write down the information about current article',
    )

    user = models.ForeignKey(
            UserModel,
            on_delete = models.CASCADE,
            # primary_key = True,
    )

    def __str__(self):
        return self.article_title

# class UserInformationModel(models.Model):
#     information_text_food_program = models.TextField(
#             blank = True,
#             null = True,
#     )
#     information_text_food_advices = models.TextField(
#             blank = True,
#             null = True,
#     )
#     information_text_tips = models.TextField(
#             blank = True,
#             null = True,
#     )
#
#     user = models.OneToOneField(
#             UserModel,
#             on_delete = models.CASCADE,
#             primary_key = True,
#
#
#     )

nutrition_blog/templates/base/base.html
{% load articles_check %}


<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="/static/css/base.css">
    <!--<link rel="stylesheet" href="/static/css/reset.css">
    <link rel="stylesheet" href="/static/css/components.css">
    <link rel="stylesheet" href="/static/css/footer.css">
    <link rel="stylesheet" href="/static/css/navigation.css">
    <link rel="stylesheet" href="/static/css/typography.css">
    <link rel="stylesheet" href="/static/css/article.css">
    <link rel="stylesheet" href="/static/css/consultant.css">
    <link rel="stylesheet" href="/static/css/hero.css">
    <link rel="stylesheet" href="/static/css/edit_profile.css">
    <link rel="stylesheet" href="/static/css/delete_account.css">
    <link rel="stylesheet" href="/static/css/login.css">-->

    <title>Nutritional Therapy Association USA - Ivelina Genova Nutrition</title>
</head>
<body>
<header class="header">

    <div class="header__logo">
        <p class="header__logo_name">Ivelina Genova</p>
        <p class="header__logo_nutrition">N U T R I T I O N</p>

        <p class="header__logo_motivation">" Begin your health journey "</p>
    </div>


    <!--    <button class="btn mobile-menu"><i class="fas fa-bars"></i></button>-->
    {% if user.is_authenticated %}
        <nav class="header__nav">
        <ul class="nav__list">
        {% with user.articles_set.all as articles_list %}
            {% if articles_list %}
                <li class="nav__item">
                    <a class="nav__itemlink" href="{% url 'user home page' user.pk %}">Home</a>
                </li>
            {% endif %}

            <li class="nav__item">
                <a class="nav__itemlink" href="{% url 'consultant' %}">Consultants</a>

            </li>

            <li class="nav__item">
                <a class="nav__itemlink" href="{% url 'edit profile' user.pk %}">Profile</a>
            </li>

            <li class="nav__item">
                <a class="nav__itemlink" href="{% url 'about page' %}">About</a>
            </li>

            <li class="nav__item">
                <a class="nav__itemlink" href="{% url 'user logout' %}">Log out</a>
            </li>
        {% endwith %}
    {% endif %}


    <!--            <li class="nav__item">
        <a class="nav__itemlink" href="blog_page.html">Blog</a>
    </li>
    <li class="nav__item">
        <a class="nav__itemlink" href="book_page.html">Book</a>
    </li>
    <li class="nav__item">
        <a class="nav__itemlink" href="resources_page.html">Resources</a>
                    <li class="nav__item">
        <a class="nav__itemlink" href="contacts_page.html">Contact</a>
    </li>
    </li>-->

    </ul>

    </nav>
</header>


<main>

    {% block page_content %}
    {% endblock %}


</main>

{% block articles_paginator %}
{% endblock %}
<footer class="footer">
    <div class="info">
        <ul class="socials">
            <li class="socials__item">
                <a href="https://m.facebook.com/Mamatatiaz/"><i class="fab fa-facebook-f"></i></a>
            </li>
            <li class="socials__item">
                <a href="https://www.instagram.com/mama_tate_i_az/"><i class="fab fa-instagram"></i></a>
            </li>
            <!--  <li class="socials__item">
                <a href=""><i class="fab fa-twitter"></i></a>
              </li>
              <li class="socials__item">
                <a href=""><i class="fab fa-google-plus-g"></i></a>
              </li>
              <li class="socials__item">
                <a href=""><i class="fab fa-youtube"></i></a>
              </li> -->

        </ul>
        <p>© 2022 - All Rights Reserved. <br/>Ivelina Genova Nutrition.</p>
    </div>

</footer>
</body>
</html>